perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Criar.as_view(), name='criar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

perfil/templates/perfil/atualizar.html
{% extends 'perfil/criar.html' %}

{% block titulo %}Atualizar perfil de {{ user }} | {% endblock %}

{% block titulocadastro %}
<h4>Atualizar cadastro</h4>
<p>
    Utilize o formulário a seguir para atualizar seus dados.
</p>
{% endblock %}

perfil/templates/perfil/criar.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block titulo %}Criar perfil | {% endblock %}

{% block conteudo %}

<div class="row">

    {% if not request.user.is_authenticated %}
    <div class="col-lg mt-3">
        <h4>Login</h4>
        <p>Se você já fez cadastro, basta entrar com seu usuário e senha abaixo:</p>

        <form method="POST" action="{% url 'perfil:login' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="InputUsuario1">Usuário</label>
                <input type="text" name='username' class="form-control" id="InputUsuario1"
                    aria-describedby="usuarioHelp" placeholder="Digite seu usuário">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Senha:</label>
                <input name='password' type="password" class="form-control" id="exampleInputPassword1"
                    placeholder="Digite sua senha">
            </div>
            <button type="submit" class="btn btn-primary btn-block btn-lg">Entrar</button>
        </form>


    </div>
    {% endif %}

    <div class="col-lg mt-3">

        {% block titulocadastro %}
        <h4>Cadastro</h4>
        <p>
            Caso ainda não tenha cadastro, utilize o formulário a seguir para se
            cadastrar
        </p>
        {% endblock %}

        <form method="POST" action="">
            {% csrf_token %}
            {{ userform|crispy }}
            {{ perfilform|crispy }}

            <div class="row">
                <div class="col">
                    <button type="submit" class='btn btn-primary btn-block btn-lg'>
                        Enviar
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}